const mongoose = require('mongoose');
const { getMongooseCore } = require('../config/db');

function getModelConnection() {
  try {
    return getMongooseCore();
  } catch (error) {
    throw new Error('[Core V3 IELTSItem] Database connection not established. Call connectCoreDB() first.');
  }
}

const ieltsItemSchema = new (getModelConnection().Schema)({
  type: {
    type: String,
    required: true,
    enum: ['reading', 'listening', 'writing-task1', 'writing-task2', 'speaking'],
    index: true,
  },
  topic: {
    type: String,
    required: true,
    trim: true,
    index: true,
  },
  difficulty: {
    type: String,
    enum: ['A1', 'A2', 'B1', 'B2', 'C1', 'C2'],
    required: true,
    index: true,
  },
  content: {
    type: Map,
    of: mongoose.Schema.Types.Mixed,
    required: true,
  },
  autoGenerated: {
    type: Boolean,
    default: false,
  },
  tags: [{
    type: String,
    trim: true,
  }],
  isActive: {
    type: Boolean,
    default: true,
    index: true,
  },
  usageCount: {
    type: Number,
    default: 0,
  },
  metadata: {
    type: Map,
    of: String,
    default: {},
  },
}, {
  timestamps: true,
});

// Indexes
ieltsItemSchema.index({ type: 1, difficulty: 1 });
ieltsItemSchema.index({ topic: 1 });
ieltsItemSchema.index({ isActive: 1, createdAt: -1 });
ieltsItemSchema.index({ tags: 1 });

function getIELTSItemModel() {
  const mongooseCore = getModelConnection();
  return mongooseCore.models.IELTSItem || mongooseCore.model('IELTSItem', ieltsItemSchema);
}

const IELTSItem = getIELTSItemModel();
module.exports = IELTSItem;

