const IELTSItem = require('../models/IELTSItem');

exports.getAllItems = async (req, res) => {
  try {
    const { type, difficulty, topic, isActive, page = 1, limit = 20 } = req.query;

    const filter = {};
    if (type) filter.type = type;
    if (difficulty) filter.difficulty = difficulty;
    if (topic) filter.topic = { $regex: topic, $options: 'i' };
    if (isActive !== undefined) filter.isActive = isActive === 'true';

    const skip = (parseInt(page) - 1) * parseInt(limit);
    const items = await IELTSItem.find(filter)
      .sort({ createdAt: -1 })
      .skip(skip)
      .limit(parseInt(limit));

    const total = await IELTSItem.countDocuments(filter);

    return res.status(200).json({
      success: true,
      message: 'Items retrieved successfully',
      data: {
        items,
        pagination: {
          page: parseInt(page),
          limit: parseInt(limit),
          total,
          pages: Math.ceil(total / parseInt(limit)),
        },
      },
    });
  } catch (error) {
    console.error('[Core V3 Item] Get all items error:', error);
    return res.status(500).json({
      success: false,
      message: 'Server error retrieving items',
      error: process.env.NODE_ENV === 'development' ? error.message : undefined,
    });
  }
};

exports.getItemById = async (req, res) => {
  try {
    const { id } = req.params;
    const item = await IELTSItem.findById(id);

    if (!item) {
      return res.status(404).json({
        success: false,
        message: 'Item not found',
      });
    }

    return res.status(200).json({
      success: true,
      message: 'Item retrieved successfully',
      data: { item },
    });
  } catch (error) {
    console.error('[Core V3 Item] Get item by ID error:', error);
    return res.status(500).json({
      success: false,
      message: 'Server error retrieving item',
      error: process.env.NODE_ENV === 'development' ? error.message : undefined,
    });
  }
};

exports.createItem = async (req, res) => {
  try {
    const { type, topic, difficulty, content, tags, autoGenerated } = req.body;

    if (!type || !topic || !difficulty || !content) {
      return res.status(400).json({
        success: false,
        message: 'Missing required fields: type, topic, difficulty, content',
      });
    }

    const item = new IELTSItem({
      type,
      topic,
      difficulty,
      content,
      tags: tags || [],
      autoGenerated: autoGenerated || false,
    });

    await item.save();

    return res.status(201).json({
      success: true,
      message: 'Item created successfully',
      data: { item },
    });
  } catch (error) {
    console.error('[Core V3 Item] Create item error:', error);
    return res.status(500).json({
      success: false,
      message: 'Server error creating item',
      error: process.env.NODE_ENV === 'development' ? error.message : undefined,
    });
  }
};

exports.updateItem = async (req, res) => {
  try {
    const { id } = req.params;
    const updates = req.body;

    const item = await IELTSItem.findByIdAndUpdate(id, updates, {
      new: true,
      runValidators: true,
    });

    if (!item) {
      return res.status(404).json({
        success: false,
        message: 'Item not found',
      });
    }

    return res.status(200).json({
      success: true,
      message: 'Item updated successfully',
      data: { item },
    });
  } catch (error) {
    console.error('[Core V3 Item] Update item error:', error);
    return res.status(500).json({
      success: false,
      message: 'Server error updating item',
      error: process.env.NODE_ENV === 'development' ? error.message : undefined,
    });
  }
};

exports.deleteItem = async (req, res) => {
  try {
    const { id } = req.params;
    const item = await IELTSItem.findByIdAndDelete(id);

    if (!item) {
      return res.status(404).json({
        success: false,
        message: 'Item not found',
      });
    }

    return res.status(200).json({
      success: true,
      message: 'Item deleted successfully',
    });
  } catch (error) {
    console.error('[Core V3 Item] Delete item error:', error);
    return res.status(500).json({
      success: false,
      message: 'Server error deleting item',
      error: process.env.NODE_ENV === 'development' ? error.message : undefined,
    });
  }
};

