const mongoose = require('mongoose');

const ieltsItemSchema = new mongoose.Schema({
  type: {
    type: String,
    required: true,
    enum: ['reading', 'writing', 'speaking', 'listening'],
    index: true
  },
  topic: {
    type: String,
    required: true,
    trim: true
  },
  content: {
    type: mongoose.Schema.Types.Mixed,
    required: true
    // Structure varies by type:
    // - writing: { question, sampleAnswer, band9Answer }
    // - reading: { passage, questions: [...] }
    // - listening: { audioUrl, questions: [...] }
    // - speaking: { prompts: [...], sampleAnswers: [...] }
  },
  createdAt: {
    type: Date,
    default: Date.now,
    index: true
  },
  autoGenerated: {
    type: Boolean,
    default: false,
    index: true
  },
  usageCount: {
    type: Number,
    default: 0,
    index: true
  },
  usedBy: [{
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    index: true
  }],
  isActive: {
    type: Boolean,
    default: true,
    index: true
  },
  metadata: {
    difficulty: {
      type: String,
      enum: ['easy', 'medium', 'hard'],
      default: 'medium'
    },
    bandLevel: {
      type: Number,
      min: 4.0,
      max: 9.0,
      default: 6.5
    },
    tags: [String],
    source: String // 'ai', 'admin', 'manual'
  }
}, {
  timestamps: true
});

// Compound indexes for efficient queries
ieltsItemSchema.index({ isActive: 1, type: 1 });
ieltsItemSchema.index({ isActive: 1, usageCount: 1 });
ieltsItemSchema.index({ usedBy: 1, isActive: 1 });

module.exports = mongoose.model('IELTSItem', ieltsItemSchema);

