/**
 * IELTS Item Generator Service
 * Generates new IELTS test items using AI (OpenAI/Gemini)
 */

let OpenAI = null;
try {
  OpenAI = require('openai');
} catch (_) {
  OpenAI = null;
}

const ENV = {
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || '',
  OPENAI_API_BASE: process.env.OPENAI_API_BASE || 'https://api.openai.com/v1',
  OPENAI_MODEL: process.env.OPENAI_MODEL || 'gpt-4o-mini',
  OPENAI_TEMPERATURE: parseFloat(process.env.OPENAI_TEMPERATURE || '0.85'),
};

const openai = (ENV.OPENAI_API_KEY && OpenAI)
  ? new OpenAI({
      apiKey: ENV.OPENAI_API_KEY,
      baseURL: ENV.OPENAI_API_BASE,
    })
  : null;

/**
 * Generate a new IELTS item based on type
 * @param {string} type - 'writing' | 'reading' | 'listening' | 'speaking'
 * @returns {Promise<object>} New IELTS item object
 */
async function generateIELTSItem(type = 'writing') {
  try {
    if (!openai) {
      console.warn('[IELTS Generator] OpenAI not configured, using fallback');
      return generateFallbackItem(type);
    }

    const prompt = getGenerationPrompt(type);
    
    const response = await openai.chat.completions.create({
      model: ENV.OPENAI_MODEL,
      temperature: ENV.OPENAI_TEMPERATURE,
      messages: [
        {
          role: 'system',
          content: 'You are an expert IELTS test creator. Always respond with valid JSON format only, no additional text.'
        },
        {
          role: 'user',
          content: prompt
        }
      ],
      max_tokens: 2000,
      response_format: { type: 'json_object' }
    });

    const result = JSON.parse(response.choices[0].message.content);
    
    return formatIELTSItem(type, result);
  } catch (error) {
    console.error('[IELTS Generator] Error generating item:', error);
    return generateFallbackItem(type);
  }
}

/**
 * Get generation prompt based on item type
 */
function getGenerationPrompt(type) {
  const prompts = {
    writing: `Generate a new IELTS Writing Task 2 question. Return JSON with:
{
  "topic": "Main topic (e.g., 'Education', 'Environment', 'Technology')",
  "question": "The full question prompt",
  "band9Answer": "A sample band 9 answer (200-300 words)",
  "keyPoints": ["Point 1", "Point 2", "Point 3"],
  "difficulty": "easy|medium|hard",
  "bandLevel": 6.5
}`,

    reading: `Generate a new IELTS Reading passage with questions. Return JSON with:
{
  "topic": "Main topic",
  "passage": "A 500-800 word passage",
  "questions": [
    {
      "type": "multiple-choice|true-false|matching|fill-blank",
      "question": "Question text",
      "options": ["Option A", "Option B", "Option C", "Option D"],
      "correctAnswer": "Option A",
      "explanation": "Why this answer is correct"
    }
  ],
  "difficulty": "easy|medium|hard",
  "bandLevel": 6.5
}`,

    listening: `Generate a new IELTS Listening test. Return JSON with:
{
  "topic": "Main topic",
  "transcript": "A 300-500 word conversation or monologue transcript",
  "questions": [
    {
      "type": "multiple-choice|fill-blank|matching",
      "question": "Question text",
      "options": ["Option A", "Option B", "Option C"],
      "correctAnswer": "Option A",
      "audioCues": "Time markers or cues"
    }
  ],
  "difficulty": "easy|medium|hard",
  "bandLevel": 6.5
}`,

    speaking: `Generate a new IELTS Speaking test prompts. Return JSON with:
{
  "topic": "Main topic",
  "part1": [
    {
      "question": "Question for Part 1",
      "sampleAnswer": "Sample answer"
    }
  ],
  "part2": {
    "cueCard": "Describe a...",
    "points": ["Point 1", "Point 2", "Point 3"],
    "sampleAnswer": "Sample 2-minute answer"
  },
  "part3": [
    {
      "question": "Follow-up question",
      "sampleAnswer": "Sample answer"
    }
  ],
  "difficulty": "easy|medium|hard",
  "bandLevel": 6.5
}`
  };

  return prompts[type] || prompts.writing;
}

/**
 * Format AI response into IELTSItem structure
 */
function formatIELTSItem(type, aiResponse) {
  const topics = [
    'Education', 'Environment', 'Technology', 'Health', 'Society',
    'Culture', 'Business', 'Travel', 'Media', 'Science'
  ];
  
  const randomTopic = topics[Math.floor(Math.random() * topics.length)];
  
  return {
    type,
    topic: aiResponse.topic || randomTopic,
    content: {
      ...aiResponse,
      generatedAt: new Date().toISOString()
    },
    autoGenerated: true,
    usageCount: 0,
    usedBy: [],
    isActive: true,
    metadata: {
      difficulty: aiResponse.difficulty || 'medium',
      bandLevel: aiResponse.bandLevel || 6.5,
      tags: [type, aiResponse.topic || randomTopic],
      source: 'ai'
    },
    createdAt: new Date()
  };
}

/**
 * Generate fallback item when AI is not available
 */
function generateFallbackItem(type) {
  const fallbackItems = {
    writing: {
      type: 'writing',
      topic: 'Education',
      content: {
        topic: 'Education',
        question: 'Some people believe that university education should be free for all students. Others argue that students should pay for their own education. Discuss both views and give your own opinion.',
        band9Answer: 'Education is a fundamental right that should be accessible to all, regardless of financial background. While some argue that free university education would strain public resources, I believe the long-term benefits to society outweigh the costs. Free education promotes social mobility, reduces inequality, and creates a more skilled workforce that drives economic growth.',
        keyPoints: [
          'Free education promotes equality and social mobility',
          'Public investment in education benefits the economy',
          'Students can contribute through taxes after graduation'
        ],
        difficulty: 'medium',
        bandLevel: 6.5
      },
      autoGenerated: true,
      usageCount: 0,
      usedBy: [],
      isActive: true,
      metadata: {
        difficulty: 'medium',
        bandLevel: 6.5,
        tags: ['writing', 'Education'],
        source: 'fallback'
      }
    },
    reading: {
      type: 'reading',
      topic: 'Science',
      content: {
        topic: 'Science',
        passage: 'Climate change is one of the most pressing issues of our time. Scientists have been studying the effects of greenhouse gases on the Earth\'s atmosphere for decades. The evidence shows that human activities, particularly the burning of fossil fuels, have significantly increased the concentration of carbon dioxide in the atmosphere.',
        questions: [
          {
            type: 'multiple-choice',
            question: 'What is the main cause of increased carbon dioxide?',
            options: ['Natural processes', 'Burning fossil fuels', 'Ocean currents', 'Solar activity'],
            correctAnswer: 'Burning fossil fuels',
            explanation: 'The passage explicitly states that burning fossil fuels has increased CO2 concentration.'
          }
        ],
        difficulty: 'medium',
        bandLevel: 6.5
      },
      autoGenerated: true,
      usageCount: 0,
      usedBy: [],
      isActive: true,
      metadata: {
        difficulty: 'medium',
        bandLevel: 6.5,
        tags: ['reading', 'Science'],
        source: 'fallback'
      }
    },
    listening: {
      type: 'listening',
      topic: 'Travel',
      content: {
        topic: 'Travel',
        transcript: 'Welcome to today\'s travel guide. Today we\'ll be discussing the best ways to explore a new city. First, consider using public transportation...',
        questions: [
          {
            type: 'multiple-choice',
            question: 'What is the main topic?',
            options: ['Hotels', 'Public transportation', 'Restaurants', 'Shopping'],
            correctAnswer: 'Public transportation',
            audioCues: '0:15-0:30'
          }
        ],
        difficulty: 'medium',
        bandLevel: 6.5
      },
      autoGenerated: true,
      usageCount: 0,
      usedBy: [],
      isActive: true,
      metadata: {
        difficulty: 'medium',
        bandLevel: 6.5,
        tags: ['listening', 'Travel'],
        source: 'fallback'
      }
    },
    speaking: {
      type: 'speaking',
      topic: 'Hobbies',
      content: {
        topic: 'Hobbies',
        part1: [
          {
            question: 'Do you have any hobbies?',
            sampleAnswer: 'Yes, I enjoy reading and playing sports in my free time.'
          }
        ],
        part2: {
          cueCard: 'Describe a hobby you enjoy. You should say: what it is, when you started it, why you like it, and explain how it benefits you.',
          points: ['What the hobby is', 'When you started', 'Why you like it', 'Benefits'],
          sampleAnswer: 'I\'d like to talk about my hobby of photography...'
        },
        part3: [
          {
            question: 'Why do people have hobbies?',
            sampleAnswer: 'People have hobbies to relax, learn new skills, and meet like-minded people.'
          }
        ],
        difficulty: 'medium',
        bandLevel: 6.5
      },
      autoGenerated: true,
      usageCount: 0,
      usedBy: [],
      isActive: true,
      metadata: {
        difficulty: 'medium',
        bandLevel: 6.5,
        tags: ['speaking', 'Hobbies'],
        source: 'fallback'
      }
    }
  };

  return fallbackItems[type] || fallbackItems.writing;
}

module.exports = {
  generateIELTSItem
};

