const bcrypt = require('bcryptjs');
const { connectCoreDB } = require('../config/db');
const User = require('../models/User');
const IELTSItem = require('../models/IELTSItem');
const SystemConfig = require('../models/SystemConfig');

async function seed() {
  try {
    console.log('[Core V3 Seed] Starting seed process...');

    // Connect to database
    await connectCoreDB();
    console.log('[Core V3 Seed] Database connected');

    // Seed admin account
    const adminEmail = 'admin@ielts-platform.com';
    const adminPassword = 'admin123';
    const existingAdmin = await User.findOne({ email: adminEmail });

    if (!existingAdmin) {
      const hashedPassword = await bcrypt.hash(adminPassword, 10);
      const admin = new User({
        email: adminEmail,
        name: 'System Admin',
        password: hashedPassword,
        role: 'admin',
        isActive: true,
      });
      await admin.save();
      console.log('[Core V3 Seed] Admin account created:', adminEmail);
    } else {
      console.log('[Core V3 Seed] Admin account already exists');
    }

    // Seed IELTS items
    const itemCount = await IELTSItem.countDocuments();
    if (itemCount === 0) {
      const sampleItems = [
        {
          type: 'reading',
          topic: 'Environmental Science',
          difficulty: 'B2',
          content: {
            title: 'The Impact of Climate Change on Arctic Wildlife',
            passage: 'Climate change has significantly affected Arctic wildlife populations. Polar bears, seals, and other species are facing habitat loss due to melting ice caps. Scientists have observed a 30% decline in polar bear populations over the past decade.',
            questions: [
              {
                type: 'multiple-choice',
                question: 'What is the main cause of polar bear habitat loss?',
                options: ['Hunting', 'Pollution', 'Ice melt', 'Disease'],
                answer: 'Ice melt',
              },
            ],
          },
          autoGenerated: false,
          tags: ['climate change', 'arctic', 'wildlife'],
          isActive: true,
        },
        {
          type: 'writing-task2',
          topic: 'Technology and Society',
          difficulty: 'C1',
          content: {
            question: 'Some people believe that the internet has brought more problems than benefits. To what extent do you agree or disagree?',
            sampleAnswer: 'The internet has revolutionized communication and access to information, but it has also introduced challenges such as privacy concerns and misinformation.',
          },
          autoGenerated: false,
          tags: ['internet', 'technology', 'society'],
          isActive: true,
        },
        {
          type: 'listening',
          topic: 'Education',
          difficulty: 'B1',
          content: {
            audioUrl: '/audio/sample-listening.mp3',
            transcript: 'Welcome to today\'s lecture on modern education systems...',
            questions: [
              {
                type: 'fill-in-blank',
                question: 'The speaker mentions that modern education focuses on _____ skills.',
                answer: 'critical thinking',
              },
            ],
          },
          autoGenerated: false,
          tags: ['education', 'listening'],
          isActive: true,
        },
        {
          type: 'speaking',
          topic: 'Daily Life',
          difficulty: 'A2',
          content: {
            prompt: 'Describe your typical day. What activities do you do from morning to evening?',
            sampleResponse: 'I usually wake up at 7 AM, have breakfast, go to work, have lunch, finish work, exercise, have dinner, and relax before bed.',
          },
          autoGenerated: false,
          tags: ['daily life', 'speaking'],
          isActive: true,
        },
        {
          type: 'writing-task1',
          topic: 'Data Analysis',
          difficulty: 'B2',
          content: {
            chartType: 'bar',
            data: {
              labels: ['2018', '2019', '2020', '2021'],
              values: [100, 120, 95, 150],
            },
            question: 'Summarize the information by selecting and reporting the main features.',
          },
          autoGenerated: false,
          tags: ['data', 'writing', 'charts'],
          isActive: true,
        },
      ];

      await IELTSItem.insertMany(sampleItems);
      console.log(`[Core V3 Seed] Seeded ${sampleItems.length} IELTS items`);
    } else {
      console.log(`[Core V3 Seed] ${itemCount} IELTS items already exist`);
    }

    // Seed system config defaults
    const defaultConfigs = [
      {
        key: 'app.name',
        value: 'IELTS Platform Core V3',
        category: 'system',
        description: 'Application name',
        isActive: true,
      },
      {
        key: 'app.version',
        value: '3.0.0',
        category: 'system',
        description: 'Application version',
        isActive: true,
      },
      {
        key: 'features.autoAssign',
        value: true,
        category: 'feature',
        description: 'Enable automatic item assignment',
        isActive: true,
      },
      {
        key: 'features.aiFeedback',
        value: true,
        category: 'feature',
        description: 'Enable AI-powered feedback',
        isActive: true,
      },
      {
        key: 'ui.theme',
        value: 'light',
        category: 'ui',
        description: 'Default UI theme',
        isActive: true,
      },
    ];

    for (const config of defaultConfigs) {
      const existing = await SystemConfig.findOne({ key: config.key });
      if (!existing) {
        await SystemConfig.create(config);
        console.log(`[Core V3 Seed] Created config: ${config.key}`);
      }
    }

    console.log('[Core V3 Seed] Seed process completed successfully');
    console.log('CORE DATABASE READY ✔');
  } catch (error) {
    console.error('[Core V3 Seed] Seed error:', error);
    throw error;
  }
}

module.exports = { seed };

// Run seed if called directly
if (require.main === module) {
  seed()
    .then(() => {
      console.log('[Core V3 Seed] Seed completed');
      process.exit(0);
    })
    .catch((error) => {
      console.error('[Core V3 Seed] Seed failed:', error);
      process.exit(1);
    });
}

