name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install root deps
        run: npm install --no-audit --no-fund
      - name: Install server deps
        run: cd server && npm install --no-audit --no-fund
      - name: Run API tests
        run: npm run test:api
      # Temporarily disable E2E tests to avoid impacting deploy pipeline
      # Re-enable when needed by uncommenting the steps below.
      # - name: Install Playwright browsers
      #   run: npx playwright install --with-deps
      # - name: Run E2E tests (deployed site)
      #   env:
      #     E2E_BASE_URL: ${{ secrets.E2E_BASE_URL }}
      #   run: npm run test:e2e


